//
//  HomeInteractor.swift
//  RappiFlix
//
//  Created by Bruno   on 21/10/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor {
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {
}
